@echo off
echo Starting AI Dashboard Project...
echo.
echo Opening Backend Server...
start "Backend Server" cmd /k "cd backend && C:/Users/HP/AppData/Local/Microsoft/WindowsApps/python3.11.exe app.py"

echo Waiting 3 seconds before starting frontend...
timeout /t 3 /nobreak >nul

echo Opening Frontend Server...
start "Frontend Server" cmd /k "npm start"

echo.
echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
echo.
echo Press any key to exit...
pause >nul